### ISSUE TITLE
Wanna use it to view logs

### ISSUE THREAD

**Issue by mayuroks** [thoughtbot/pick#54] opened 2015-04-10 10:23 UTC
Really useful tool !! I must say. I have an issue regarding viewing logs. When I do something like

```bash
cat syslog | pick

# type something
fuzzy search happens

# delete what you typed
weird sorted content shows up
```

Initially stuff looks good. as soon as you type and erase what you typed the content in the "pick buffer" gets sorted. It would be useful if the text in pick buffer remains the same.

**Comment by eavgerinos** [comment] 2015-04-10 12:25
Same with #50 imho

**Comment by calleerlandsson** [comment] 2015-04-13 07:44
Hey @mayuroks, thanks for reporting this!

If you want to try fixing it, a PR would be very welcome. If not, I'll fix it as soon as I get to it.

Since this is a duplicate of #50, I'm going to close this.

**Closed by calleerlandsson** 2015-04-13 07:44 UTC
